
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anthony
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        setDefaultButton();
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    Connection con;
    Statement st;
    
    private static final String DbName = "studywise";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/"+DbName; 
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
    
    public void Connection() throws SQLException{
        try{
        Class.forName(DbDriver);
        con = DriverManager.getConnection(DbUrl,DbUsername,DbPassword);
        st = con.createStatement();
        
        if (con != null){
            System.out.println("Connection successful");
        }
        
        } catch (ClassNotFoundException ex){
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, "Driver not found", ex);
        }
        
        
        
    }

    private void setDefaultButton() {
    getRootPane().setDefaultButton(GetStarted);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        LABEL_ToTrack = new javax.swing.JLabel();
        LABEL_S2 = new javax.swing.JLabel();
        LABEL_tudy2 = new javax.swing.JLabel();
        LABEL_W2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LABEL_S1 = new javax.swing.JLabel();
        LABEL_tudy1 = new javax.swing.JLabel();
        LABEL_W1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        GetStarted = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(241, 232, 181));

        LABEL_ToTrack.setText("To track and maintain good study habits");

        LABEL_S2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        LABEL_S2.setText("S");

        LABEL_tudy2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        LABEL_tudy2.setForeground(new java.awt.Color(133, 26, 3));
        LABEL_tudy2.setText("tudy");

        LABEL_W2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        LABEL_W2.setText("W");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(133, 26, 3));
        jLabel4.setText("ise");

        LABEL_S1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        LABEL_S1.setText("S");

        LABEL_tudy1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LABEL_tudy1.setForeground(new java.awt.Color(133, 26, 3));
        LABEL_tudy1.setText("tudy");

        LABEL_W1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        LABEL_W1.setText("W");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(133, 26, 3));
        jLabel8.setText("ise");

        GetStarted.setBackground(new java.awt.Color(126, 69, 51));
        GetStarted.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GetStarted.setForeground(new java.awt.Color(255, 255, 255));
        GetStarted.setText("Get Started");
        GetStarted.setBorderPainted(false);
        GetStarted.setFocusPainted(false);
        GetStarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetStartedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(LABEL_S1)
                        .addGap(0, 0, 0)
                        .addComponent(LABEL_tudy1)
                        .addGap(0, 0, 0)
                        .addComponent(LABEL_W1)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(LABEL_S2)
                                .addGap(0, 0, 0)
                                .addComponent(LABEL_tudy2)
                                .addGap(0, 0, 0)
                                .addComponent(LABEL_W2)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel4))
                            .addComponent(LABEL_ToTrack)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(GetStarted)))))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_S1)
                    .addComponent(LABEL_tudy1)
                    .addComponent(LABEL_W1)
                    .addComponent(jLabel8))
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LABEL_W2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LABEL_S2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LABEL_tudy2)))
                .addGap(1, 1, 1)
                .addComponent(LABEL_ToTrack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GetStarted)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GetStartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetStartedActionPerformed
        // TODO add your handling code here:
        
        Registration registration = new Registration();
        registration.setVisible(true);
        registration.pack();
        registration.setLocationRelativeTo(null);
        this.dispose();
        
        
    }//GEN-LAST:event_GetStartedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetStarted;
    private javax.swing.JLabel LABEL_S1;
    private javax.swing.JLabel LABEL_S2;
    private javax.swing.JLabel LABEL_ToTrack;
    private javax.swing.JLabel LABEL_W1;
    private javax.swing.JLabel LABEL_W2;
    private javax.swing.JLabel LABEL_tudy1;
    private javax.swing.JLabel LABEL_tudy2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
