import Classes.RoundedBorder;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anthony
 */

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setDefaultButton();
        setupEnterKeyFlow();
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    Connection con;
    Statement st;
    PreparedStatement pstmt;
    
    private static final String DbName = "studywise";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/"+DbName; 
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
    
    public void Connection() throws SQLException{
        try{
        Class.forName(DbDriver);
        con = DriverManager.getConnection(DbUrl,DbUsername,DbPassword);
        st = con.createStatement();
        
        if (con != null){
            System.out.println("Connection successful");
        }
        
        } catch (ClassNotFoundException ex){
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, "Driver not found", ex);
        }
        
    }
    
      private void setupEnterKeyFlow() {
   

    TXT_LOGUsername.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            TXT_LOGPassword.requestFocusInWindow();
        }
    });

    TXT_LOGPassword.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            BUTTON_LOGIN.doClick();
        }
    });
}  
      private void setDefaultButton() {
    getRootPane().setDefaultButton(BUTTON_LOGIN);
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_1 = new javax.swing.JPanel();
        LABEL_Signin = new javax.swing.JLabel();
        TXT_LOGUsername = new javax.swing.JTextField();
        LABEL_USERNAME = new javax.swing.JLabel();
        TXT_LOGPassword = new javax.swing.JPasswordField();
        LABEL_PASSWORD = new javax.swing.JLabel();
        BUTTON_LOGIN = new javax.swing.JButton();
        LABEL_NoAccount = new javax.swing.JLabel();
        BUTTON_MoveToRegistrationPage = new javax.swing.JButton();
        PANEL_2 = new javax.swing.JPanel();
        LABEL_Track = new javax.swing.JLabel();
        LABEL_Study = new javax.swing.JLabel();
        LABEL_S = new javax.swing.JLabel();
        LABEL_tudy = new javax.swing.JLabel();
        LABEL_W = new javax.swing.JLabel();
        LABEL_ise = new javax.swing.JLabel();
        BUTTON_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PANEL_1.setBackground(new java.awt.Color(241, 232, 181));

        LABEL_Signin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LABEL_Signin.setForeground(new java.awt.Color(133, 26, 3));
        LABEL_Signin.setText("Sign in");

        TXT_LOGUsername.setBackground(new java.awt.Color(241, 232, 181));
        TXT_LOGUsername.setBorder(new RoundedBorder(30));
        TXT_LOGUsername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TXT_LOGUsername.setPreferredSize(new java.awt.Dimension(64, 26));
        TXT_LOGUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_LOGUsernameActionPerformed(evt);
            }
        });

        LABEL_USERNAME.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LABEL_USERNAME.setText("EMAIL/USERNAME");

        TXT_LOGPassword.setBackground(new java.awt.Color(241, 232, 181));
        TXT_LOGPassword.setText("123456789");
        TXT_LOGPassword.setBorder(new RoundedBorder(30));
        TXT_LOGPassword.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TXT_LOGPassword.setPreferredSize(new java.awt.Dimension(64, 26));
        TXT_LOGPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_LOGPasswordActionPerformed(evt);
            }
        });

        LABEL_PASSWORD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LABEL_PASSWORD.setText("PASSWORD");

        BUTTON_LOGIN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_LOGIN.setForeground(new java.awt.Color(133, 26, 3));
        BUTTON_LOGIN.setText("LOGIN");
        BUTTON_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_LOGINActionPerformed(evt);
            }
        });

        LABEL_NoAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LABEL_NoAccount.setText("No Account?");

        BUTTON_MoveToRegistrationPage.setBackground(new java.awt.Color(241, 232, 181));
        BUTTON_MoveToRegistrationPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_MoveToRegistrationPage.setForeground(new java.awt.Color(133, 26, 3));
        BUTTON_MoveToRegistrationPage.setText("SIGN UP");
        BUTTON_MoveToRegistrationPage.setBorder(null);
        BUTTON_MoveToRegistrationPage.setContentAreaFilled(false);
        BUTTON_MoveToRegistrationPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_MoveToRegistrationPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANEL_1Layout = new javax.swing.GroupLayout(PANEL_1);
        PANEL_1.setLayout(PANEL_1Layout);
        PANEL_1Layout.setHorizontalGroup(
            PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TXT_LOGPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LABEL_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PANEL_1Layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(BUTTON_LOGIN))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(LABEL_NoAccount)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BUTTON_MoveToRegistrationPage, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)))
                    .addComponent(LABEL_Signin)
                    .addComponent(TXT_LOGUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABEL_USERNAME))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        PANEL_1Layout.setVerticalGroup(
            PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(LABEL_Signin)
                .addGap(30, 30, 30)
                .addComponent(TXT_LOGUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LABEL_USERNAME)
                .addGap(30, 30, 30)
                .addComponent(TXT_LOGPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LABEL_PASSWORD)
                .addGap(25, 25, 25)
                .addComponent(BUTTON_LOGIN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_NoAccount)
                    .addComponent(BUTTON_MoveToRegistrationPage))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        PANEL_2.setBackground(new java.awt.Color(255, 255, 255));

        LABEL_Track.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LABEL_Track.setText("Track and maintain good");

        LABEL_Study.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LABEL_Study.setText("Study Habits");

        LABEL_S.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        LABEL_S.setText("S");

        LABEL_tudy.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        LABEL_tudy.setForeground(new java.awt.Color(151, 83, 83));
        LABEL_tudy.setText("tudy");

        LABEL_W.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        LABEL_W.setText("W");

        LABEL_ise.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        LABEL_ise.setForeground(new java.awt.Color(151, 83, 83));
        LABEL_ise.setText("ise");

        BUTTON_Back.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BUTTON_Back.setForeground(new java.awt.Color(133, 26, 3));
        BUTTON_Back.setText("←");
        BUTTON_Back.setBorder(null);
        BUTTON_Back.setContentAreaFilled(false);
        BUTTON_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANEL_2Layout = new javax.swing.GroupLayout(PANEL_2);
        PANEL_2.setLayout(PANEL_2Layout);
        PANEL_2Layout.setHorizontalGroup(
            PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_2Layout.createSequentialGroup()
                .addGroup(PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANEL_2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PANEL_2Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(LABEL_Study))
                                    .addComponent(LABEL_Track))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_2Layout.createSequentialGroup()
                                .addComponent(LABEL_S)
                                .addGap(0, 0, 0)
                                .addComponent(LABEL_tudy)
                                .addGap(0, 0, 0)
                                .addComponent(LABEL_W)
                                .addGap(0, 0, 0)
                                .addComponent(LABEL_ise))))
                    .addGroup(PANEL_2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BUTTON_Back)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        PANEL_2Layout.setVerticalGroup(
            PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BUTTON_Back)
                .addGap(110, 110, 110)
                .addGroup(PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_S, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABEL_tudy)
                    .addComponent(LABEL_W, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABEL_ise))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABEL_Track)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABEL_Study)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PANEL_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PANEL_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANEL_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PANEL_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_LOGPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_LOGPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_LOGPasswordActionPerformed

    private void BUTTON_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_LOGINActionPerformed
        // TODO add your handling code here:
          
     String userInput = TXT_LOGUsername.getText();
    char[] passwordChars = TXT_LOGPassword.getPassword();
    String password = new String(passwordChars);

    String queryLogin = "SELECT * FROM users WHERE (username = ? OR email = ?) AND password = ?";

    try {
        pstmt = con.prepareStatement(queryLogin);
        pstmt.setString(1, userInput);
        pstmt.setString(2, userInput);
        pstmt.setString(3, password);

        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            String role = rs.getString("role");
            int userId = rs.getInt("id");
            String username = rs.getString("username");
            String email = rs.getString("email");

            JOptionPane.showMessageDialog(new JFrame(), "Logged in as " + role, "Success", JOptionPane.INFORMATION_MESSAGE);

            if (role.equalsIgnoreCase("admin")) {
                Adashboard adashboard = new Adashboard();
                adashboard.setVisible(true);
                adashboard.pack();
                adashboard.setLocationRelativeTo(null);
            } else {
                Dashboard dashboard = new Dashboard(userId);
                dashboard.setVisible(true);
                dashboard.pack();
                dashboard.setLocationRelativeTo(null);
                this.dispose();
            }

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid Credentials", "Error", JOptionPane.ERROR_MESSAGE);
        }

        rs.close();
        pstmt.close();
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        java.util.Arrays.fill(passwordChars, '\0');
    }

                        
    }//GEN-LAST:event_BUTTON_LOGINActionPerformed
   
    private void TXT_LOGUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_LOGUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_LOGUsernameActionPerformed

    private void BUTTON_MoveToRegistrationPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_MoveToRegistrationPageActionPerformed
        // TODO add your handling code here:
        
        Registration registration = new Registration();
        registration.setVisible(true);
        registration.pack();
        registration.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_BUTTON_MoveToRegistrationPageActionPerformed

    private void BUTTON_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_BackActionPerformed
        // TODO add your handling code here:
        
        Homepage homepage = new Homepage();
        homepage.setVisible(true);
        homepage.pack();
        homepage.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_BUTTON_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTON_Back;
    private javax.swing.JButton BUTTON_LOGIN;
    private javax.swing.JButton BUTTON_MoveToRegistrationPage;
    private javax.swing.JLabel LABEL_NoAccount;
    private javax.swing.JLabel LABEL_PASSWORD;
    private javax.swing.JLabel LABEL_S;
    private javax.swing.JLabel LABEL_Signin;
    private javax.swing.JLabel LABEL_Study;
    private javax.swing.JLabel LABEL_Track;
    private javax.swing.JLabel LABEL_USERNAME;
    private javax.swing.JLabel LABEL_W;
    private javax.swing.JLabel LABEL_ise;
    private javax.swing.JLabel LABEL_tudy;
    private javax.swing.JPanel PANEL_1;
    private javax.swing.JPanel PANEL_2;
    private javax.swing.JPasswordField TXT_LOGPassword;
    private javax.swing.JTextField TXT_LOGUsername;
    // End of variables declaration//GEN-END:variables
}
