import Classes.RoundedBorder;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anthony
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        setDefaultButton();
        setupEnterKeyFlow();
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    Connection con;
    Statement st;
    
    private static final String DbName = "studywise";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/"+DbName; 
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
    
    public void Connection() throws SQLException{
        try{
        Class.forName(DbDriver);
        con = DriverManager.getConnection(DbUrl,DbUsername,DbPassword);
        st = con.createStatement();
        
        if (con != null){
            System.out.println("Connection successful");
        }
        
        } catch (ClassNotFoundException ex){
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, "Driver not found", ex);
        }
        
    }
    
    private void setupEnterKeyFlow() {
        
        
    TXT_LOGemail.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            TXT_LOGusername.requestFocusInWindow();
        }
    });

    TXT_LOGusername.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            TXT_LOGpassword.requestFocusInWindow();
        }
    });

    TXT_LOGpassword.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            BUTTON_Signup.doClick();
        }
    });
}  
    private void setDefaultButton() {
    getRootPane().setDefaultButton(BUTTON_Signup);
}
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_1 = new javax.swing.JPanel();
        LABEL_Signup = new javax.swing.JLabel();
        LABEL_USERNAME = new javax.swing.JLabel();
        TXT_LOGusername = new javax.swing.JTextField();
        TXT_LOGpassword = new javax.swing.JPasswordField();
        LABEL_PASSWORD = new javax.swing.JLabel();
        BUTTON_Signup = new javax.swing.JButton();
        LABEL_AlreadyHaveAA = new javax.swing.JLabel();
        BUTTON_MoveToLoginPage = new javax.swing.JButton();
        TXT_LOGemail = new javax.swing.JTextField();
        LABEL_EMAIL = new javax.swing.JLabel();
        PANEL_2 = new javax.swing.JPanel();
        LABEL_Track = new javax.swing.JLabel();
        LABEL_Study = new javax.swing.JLabel();
        LABEL_S = new javax.swing.JLabel();
        LABEL_tudy = new javax.swing.JLabel();
        LABEL_W = new javax.swing.JLabel();
        LABEL_ise = new javax.swing.JLabel();
        BUTTON_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PANEL_1.setBackground(new java.awt.Color(241, 232, 181));

        LABEL_Signup.setBackground(new java.awt.Color(133, 26, 3));
        LABEL_Signup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LABEL_Signup.setForeground(new java.awt.Color(133, 26, 3));
        LABEL_Signup.setText("Sign up");

        LABEL_USERNAME.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LABEL_USERNAME.setText("USERNAME");

        TXT_LOGusername.setBackground(new java.awt.Color(241, 232, 181));
        TXT_LOGusername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXT_LOGusername.setBorder(new RoundedBorder(30));
        TXT_LOGusername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TXT_LOGusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_LOGusernameActionPerformed(evt);
            }
        });

        TXT_LOGpassword.setBackground(new java.awt.Color(241, 232, 181));
        TXT_LOGpassword.setText("123456789");
        TXT_LOGpassword.setBorder(new RoundedBorder(30));
        TXT_LOGpassword.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TXT_LOGpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_LOGpasswordActionPerformed(evt);
            }
        });

        LABEL_PASSWORD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LABEL_PASSWORD.setText("PASSWORD");

        BUTTON_Signup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_Signup.setForeground(new java.awt.Color(133, 26, 3));
        BUTTON_Signup.setText("Sign up");
        BUTTON_Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_SignupActionPerformed(evt);
            }
        });

        LABEL_AlreadyHaveAA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LABEL_AlreadyHaveAA.setText("Already have an account?");

        BUTTON_MoveToLoginPage.setBackground(new java.awt.Color(241, 232, 181));
        BUTTON_MoveToLoginPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_MoveToLoginPage.setForeground(new java.awt.Color(133, 26, 3));
        BUTTON_MoveToLoginPage.setText("LOGIN");
        BUTTON_MoveToLoginPage.setBorder(null);
        BUTTON_MoveToLoginPage.setContentAreaFilled(false);
        BUTTON_MoveToLoginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_MoveToLoginPageActionPerformed(evt);
            }
        });

        TXT_LOGemail.setBackground(new java.awt.Color(241, 232, 181));
        TXT_LOGemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXT_LOGemail.setBorder(new RoundedBorder(30));
        TXT_LOGemail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TXT_LOGemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_LOGemailActionPerformed(evt);
            }
        });

        LABEL_EMAIL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LABEL_EMAIL.setText("EMAIL");

        javax.swing.GroupLayout PANEL_1Layout = new javax.swing.GroupLayout(PANEL_1);
        PANEL_1.setLayout(PANEL_1Layout);
        PANEL_1Layout.setHorizontalGroup(
            PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LABEL_PASSWORD)
                        .addComponent(TXT_LOGpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_1Layout.createSequentialGroup()
                                    .addComponent(BUTTON_Signup)
                                    .addGap(76, 76, 76))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_1Layout.createSequentialGroup()
                                    .addComponent(LABEL_AlreadyHaveAA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BUTTON_MoveToLoginPage)
                                    .addGap(20, 20, 20)))))
                    .addGroup(PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TXT_LOGusername, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .addComponent(LABEL_Signup)
                        .addComponent(LABEL_USERNAME)
                        .addComponent(TXT_LOGemail)
                        .addComponent(LABEL_EMAIL)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        PANEL_1Layout.setVerticalGroup(
            PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(LABEL_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TXT_LOGemail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LABEL_EMAIL)
                .addGap(18, 18, 18)
                .addComponent(TXT_LOGusername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LABEL_USERNAME)
                .addGap(18, 18, 18)
                .addComponent(TXT_LOGpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LABEL_PASSWORD)
                .addGap(25, 25, 25)
                .addComponent(BUTTON_Signup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PANEL_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_AlreadyHaveAA)
                    .addComponent(BUTTON_MoveToLoginPage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PANEL_2.setBackground(new java.awt.Color(255, 255, 255));

        LABEL_Track.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LABEL_Track.setText("Track and maintain good");

        LABEL_Study.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LABEL_Study.setText("Study Habits");

        LABEL_S.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        LABEL_S.setText("S");

        LABEL_tudy.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        LABEL_tudy.setForeground(new java.awt.Color(151, 83, 83));
        LABEL_tudy.setText("tudy");

        LABEL_W.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        LABEL_W.setText("W");

        LABEL_ise.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        LABEL_ise.setForeground(new java.awt.Color(151, 83, 83));
        LABEL_ise.setText("ise");

        BUTTON_Back.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BUTTON_Back.setForeground(new java.awt.Color(133, 26, 3));
        BUTTON_Back.setText("←");
        BUTTON_Back.setBorder(null);
        BUTTON_Back.setBorderPainted(false);
        BUTTON_Back.setContentAreaFilled(false);
        BUTTON_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANEL_2Layout = new javax.swing.GroupLayout(PANEL_2);
        PANEL_2.setLayout(PANEL_2Layout);
        PANEL_2Layout.setHorizontalGroup(
            PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_2Layout.createSequentialGroup()
                .addGroup(PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BUTTON_Back))
                    .addGroup(PANEL_2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANEL_2Layout.createSequentialGroup()
                                .addComponent(LABEL_S)
                                .addGap(0, 0, 0)
                                .addComponent(LABEL_tudy)
                                .addGap(0, 0, 0)
                                .addComponent(LABEL_W)
                                .addGap(0, 0, 0)
                                .addComponent(LABEL_ise))
                            .addGroup(PANEL_2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(LABEL_Track))
                            .addGroup(PANEL_2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(LABEL_Study)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PANEL_2Layout.setVerticalGroup(
            PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BUTTON_Back)
                .addGap(112, 112, 112)
                .addGroup(PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABEL_tudy, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PANEL_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LABEL_S, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LABEL_W, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LABEL_ise))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LABEL_Track)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABEL_Study)
                .addGap(185, 185, 185))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PANEL_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(PANEL_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANEL_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PANEL_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON_MoveToLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_MoveToLoginPageActionPerformed
        // TODO add your handling code here:

        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_BUTTON_MoveToLoginPageActionPerformed

    private void BUTTON_SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_SignupActionPerformed
        // TODO add your handling code here:

        String username = TXT_LOGusername.getText().trim();
        String password = new String(TXT_LOGpassword.getPassword());
        String email = TXT_LOGemail.getText().trim();

        if (email.isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Email is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (username.isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Username is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (password.isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Password is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        
        System.out.println("User account created with Username: "+ username);
        
        String DbUrl = "jdbc:mysql://localhost:3306/studywise";
        String DBUsername = "root";
        String DBPassword = "";

         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection(DbUrl, DBUsername, DBPassword);
        st = con.createStatement();
            
        String queryRegister = "INSERT INTO users (username, password, email, role) VALUES (?, ?, ?, 'client')";
        try (PreparedStatement pstmt = con.prepareStatement(queryRegister)) {
            pstmt.setString(1, username);
            pstmt.setString(2, password);
            pstmt.setString(3, email);
            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(new JFrame(), "Account created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        
            TXT_LOGusername.setText("");
            TXT_LOGpassword.setText("");
            TXT_LOGemail.setText("");
        }
        
         } catch (ClassNotFoundException | SQLException e) {
        Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, "Database Error", e);
        JOptionPane.showMessageDialog(new JFrame(), "Account creation failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BUTTON_SignupActionPerformed

    private void TXT_LOGpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_LOGpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_LOGpasswordActionPerformed

    private void TXT_LOGusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_LOGusernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TXT_LOGusernameActionPerformed

    private void BUTTON_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_BackActionPerformed
        // TODO add your handling code here:
        
        Homepage homepage = new Homepage();
        homepage.setVisible(true);
        homepage.pack();
        homepage.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_BUTTON_BackActionPerformed

    private void TXT_LOGemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_LOGemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_LOGemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTON_Back;
    private javax.swing.JButton BUTTON_MoveToLoginPage;
    private javax.swing.JButton BUTTON_Signup;
    private javax.swing.JLabel LABEL_AlreadyHaveAA;
    private javax.swing.JLabel LABEL_EMAIL;
    private javax.swing.JLabel LABEL_PASSWORD;
    private javax.swing.JLabel LABEL_S;
    private javax.swing.JLabel LABEL_Signup;
    private javax.swing.JLabel LABEL_Study;
    private javax.swing.JLabel LABEL_Track;
    private javax.swing.JLabel LABEL_USERNAME;
    private javax.swing.JLabel LABEL_W;
    private javax.swing.JLabel LABEL_ise;
    private javax.swing.JLabel LABEL_tudy;
    private javax.swing.JPanel PANEL_1;
    private javax.swing.JPanel PANEL_2;
    private javax.swing.JTextField TXT_LOGemail;
    private javax.swing.JPasswordField TXT_LOGpassword;
    private javax.swing.JTextField TXT_LOGusername;
    // End of variables declaration//GEN-END:variables
}
